---
name: Recorridos sobre listas
locale: es
type: learning
beta: true
teacher_info: ''
language: gobstones
id_format: '%05d'
order:
- 100
- 200
- 300
- 400
- 500
- 600
- 700
- 800
- 900
- 1000
- 1100
- 1200
- 1300
